/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.userscreen;

/**
 *
 * @author Grapess
 */
public class MyFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form MyFrame
     */
    public MyFrame() {
        initComponents();
        setSize(500, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel1 = new screens.userscreen.BackPanel();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout backPanel1Layout = new javax.swing.GroupLayout(backPanel1);
        backPanel1.setLayout(backPanel1Layout);
        backPanel1Layout.setHorizontalGroup(
            backPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jButton1)
                .addContainerGap(539, Short.MAX_VALUE))
        );
        backPanel1Layout.setVerticalGroup(
            backPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jButton1)
                .addContainerGap(354, Short.MAX_VALUE))
        );

        getContentPane().add(backPanel1);
        backPanel1.setBounds(0, 0, 740, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private screens.userscreen.BackPanel backPanel1;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
