/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.userscreen;

import operations.CommonOperations;

/**
 *
 * @author Grapess
 */
public class UserMainScreen extends javax.swing.JFrame {

    private String username;
    public UserMainScreen() {
        initComponents();
        setSize(1200,650);
        setLocationRelativeTo(null);
    }
    public UserMainScreen(String username){
        this();
        this.username = username;
        setTitle("Welcome : " + username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myDesktopPane1 = new screens.userscreen.MyDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jmiOpen = new javax.swing.JMenuItem();
        jmiViewStudentDetails = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiViewStudentReport = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(myDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenu3.setText("Operations");

        jmiOpen.setText("Open Frames");
        jmiOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOpenActionPerformed(evt);
            }
        });
        jMenu3.add(jmiOpen);

        jmiViewStudentDetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmiViewStudentDetails.setText("View Student Details");
        jmiViewStudentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewStudentDetailsActionPerformed(evt);
            }
        });
        jMenu3.add(jmiViewStudentDetails);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Reports");

        jmiViewStudentReport.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jmiViewStudentReport.setText("View Student Course Report");
        jmiViewStudentReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewStudentReportActionPerformed(evt);
            }
        });
        jMenu1.add(jmiViewStudentReport);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItem1.setText("View Course Report");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOpenActionPerformed
        CommonOperations.showInternalFrame(myDesktopPane1, new MyFrame());
    }//GEN-LAST:event_jmiOpenActionPerformed

    private void jmiViewStudentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewStudentDetailsActionPerformed
        CommonOperations.showInternalFrame(myDesktopPane1, new ViewStudentDetails());
    }//GEN-LAST:event_jmiViewStudentDetailsActionPerformed

    private void jmiViewStudentReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewStudentReportActionPerformed
        CommonOperations.showInternalFrame(myDesktopPane1, new ViewCourseReport());
    }//GEN-LAST:event_jmiViewStudentReportActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CommonOperations.showInternalFrame(myDesktopPane1, new ViewCourseChart());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmiOpen;
    private javax.swing.JMenuItem jmiViewStudentDetails;
    private javax.swing.JMenuItem jmiViewStudentReport;
    private screens.userscreen.MyDesktopPane myDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
