/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.userscreen;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import model.dao.CoursesDAO;
import model.to.CoursesTO;
import operations.JasperReportGenerator;

/**
 *
 * @author Grapess
 */
public class ViewCourseReport extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewCourseReport
     */
    public ViewCourseReport() {
        initComponents();
        List<CoursesTO> courses = new CoursesDAO().getAllRecord();
        jcbCourse.removeAllItems();
        jcbCourse.addItem("Choose Any Course");
        if(courses!=null && courses.size()>0){
            for(CoursesTO ct : courses){
                jcbCourse.addItem(ct);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbCourse = new javax.swing.JComboBox();
        btnView = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Reports");

        jcbCourse.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jcbCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnView.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnView.setText("View Student Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jcbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        if(jcbCourse.getSelectedIndex()>0){
            CoursesTO ct = (CoursesTO) jcbCourse.getSelectedItem();
            String path = getClass().getResource("/screens/userscreen/coursereport.jrxml").getPath();
            JasperReportGenerator generator = new JasperReportGenerator(path);
            Map parameters = new HashMap();
            parameters.put("cid", ct.getCourseid());
            generator.generateReport(parameters);
        }
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox jcbCourse;
    // End of variables declaration//GEN-END:variables
}
