/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.userscreen;

import screens.adminscreen.*;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Date;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import model.dao.CommonDAO;
import model.dao.StudentCoursesDAO;
import model.dao.StudentPhotosDAO;
import model.dao.StudentsDAO;
import model.to.StudentPhotosTO;
import model.to.StudentsTO;
import operations.CommonOperations;
import operations.ErrorHandler;
import operations.Validations;

/**
 *
 * @author Grapess
 */
public class ViewStudentDetails extends javax.swing.JInternalFrame {

    private String image_path;
    private List<StudentsTO> students;
    private int index;

    public ViewStudentDetails() {
        initComponents();
        jcbMaritalStaus.removeAllItems();
        jcbMaritalStaus.addItem("Choose Marital Status");
        jcbMaritalStaus.addItem("Single");
        jcbMaritalStaus.addItem("Married");
        index = -1;
        students = new StudentsDAO().getAllRecord();
        if (students != null && students.size() > 0) {
            index = 0;
            showDetails(index);
        }
    }

    private void showDetails(int index_value) {
        if (students != null && index_value < students.size()) {
            StudentsTO record = students.get(index_value);
            lblStudentID.setText(String.valueOf(record.getStudentid()));
            jtfName.setText(record.getStudentname());
            jtfFatherName.setText(record.getFathername());
            jtfContactNo.setText(record.getContactno());
            cdpDob.setDate(record.getDob());
            for (int i = 1; i < jcbMaritalStaus.getItemCount(); i++) {
                String value = jcbMaritalStaus.getItemAt(i).toString();
                if (value.equalsIgnoreCase(record.getMaritalstatus())) {
                    jcbMaritalStaus.setSelectedIndex(i);
                    break;
                }
            }
            groupGender.clearSelection();
            JRadioButton[] radios = {jrbMale, jrbFeMale, jrbOthers};
            for (JRadioButton radio : radios) {
                if (radio.getText().equalsIgnoreCase(record.getGender())) {
                    radio.setSelected(true);
                    break;
                }
            }
            try {
                boolean notfound = true;
                if (record.getPhotoid() != 0) {
                    StudentPhotosTO photo = new StudentPhotosDAO().getRecord(record.getPhotoid());
                    if (photo != null) {
                        notfound = false;
                        BufferedImage img;
                        img = ImageIO.read(photo.getPhotodata());
                        Image dimg = img.getScaledInstance(350, 350, Image.SCALE_SMOOTH);
                        ImageIcon icon = new ImageIcon(dimg);
                        lblPic.setIcon(icon);
                    }
                }
                if (notfound) {
                    ImageIcon icon;
                    icon = new ImageIcon(getClass().getResource("/pics/no_image.gif"));
                    lblPic.setIcon(icon);
                }
            } catch (Exception ex) {
                ErrorHandler.showStackTrace(ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupGender = new javax.swing.ButtonGroup();
        lblPic = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfFatherName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfContactNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbMaritalStaus = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jrbMale = new javax.swing.JRadioButton();
        jrbOthers = new javax.swing.JRadioButton();
        jrbFeMale = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        cdpDob = new controls.CurrentDatePanel();
        btnChoose = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblStudentID = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Students");

        lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/no_image.gif"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText("Enter Name :");

        jtfName.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel2.setText("Enter Father Name :");

        jtfFatherName.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel3.setText("Enter Contact No :");

        jtfContactNo.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jtfContactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfContactNoKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel4.setText("Choose Marital Status :");

        jcbMaritalStaus.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jcbMaritalStaus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel5.setText("Choose Gender :");

        groupGender.add(jrbMale);
        jrbMale.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jrbMale.setText("Male");

        groupGender.add(jrbOthers);
        jrbOthers.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jrbOthers.setText("Others");

        groupGender.add(jrbFeMale);
        jrbFeMale.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jrbFeMale.setText("FeMale");

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel6.setText("Choose Date Of Birth :");

        btnChoose.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnChoose.setText("Choose Pics...");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel7.setText("Student ID :");

        lblStudentID.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblStudentID.setText("Enter Name :");

        btnPrevious.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnUpdate.setText("Update Details");

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnDelete.setText("Delete Record");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfContactNo, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                                    .addComponent(jcbMaritalStaus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jrbMale)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbFeMale)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbOthers))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStudentID)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfFatherName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cdpDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblStudentID)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jcbMaritalStaus, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblPic))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jrbMale)
                            .addComponent(jrbOthers)
                            .addComponent(jrbFeMale)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cdpDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        JFileChooser jfc = new JFileChooser();
        int result = jfc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String path = jfc.getSelectedFile().getAbsolutePath();
            if (Validations.isValidImage(path)) {
                image_path = path;
                try {
                    BufferedImage img;
                    img = ImageIO.read(new File(image_path));
                    Image dimg = img.getScaledInstance(lblPic.getWidth(), lblPic.getHeight(), Image.SCALE_SMOOTH);
                    ImageIcon icon = new ImageIcon(dimg);
                    lblPic.setIcon(icon);
                } catch (Exception ex) {
                    image_path = null;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Format of Image Selected");
            }
        }
    }//GEN-LAST:event_btnChooseActionPerformed

    private void jtfContactNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContactNoKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfContactNoKeyTyped

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        if (index != -1 && index != 0 && students != null && students.size() > 0) {
            index--;
            showDetails(index);
        } else {
            JOptionPane.showMessageDialog(this, "There is no Previous Record");
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (index != -1 && students != null && students.size() > 0 && index < students.size() - 1) {
            index++;
            showDetails(index);
        } else {
            JOptionPane.showMessageDialog(this, "There is no Next Record");
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (index >= 0 && students != null && index < students.size()) {
            int result = JOptionPane.showConfirmDialog(this, "Are You Sure To Removed This Record?", "Message From Admin", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                StudentsTO record = students.get(index);
                StudentCoursesDAO sc_action = new StudentCoursesDAO();
                String message = "";
                if (sc_action.isCourseAlloted(record.getStudentid())) {
                    message = "This Student enroll in a Course. So Developer cannot delete the record";
                } else {
                    boolean delete_status = true;
                    if (record.getPhotoid() != 0) {
                        StudentPhotosDAO sp_action = new StudentPhotosDAO();
                        delete_status = sp_action.deleteRecord(record.getPhotoid());
                    }
                    if (delete_status) {
                        StudentsDAO action = new StudentsDAO();
                        if (action.deleteRecord(record.getStudentid())) {
                            message = "Record is Removed From System";
                            students = action.getAllRecord();
                            if(students!=null && students.size()>0){
                                index = 0;
                                showDetails(index);
                            }else{
                                index = -1;
                            }
                        }else{
                            message = "Deletion failure. " + action.getError_message();
                        }
                    } else {
                        message = "There is issue in Photo Deletion";
                    }

                }
                JOptionPane.showMessageDialog(this, message);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnUpdate;
    private controls.CurrentDatePanel cdpDob;
    private javax.swing.ButtonGroup groupGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox jcbMaritalStaus;
    private javax.swing.JRadioButton jrbFeMale;
    private javax.swing.JRadioButton jrbMale;
    private javax.swing.JRadioButton jrbOthers;
    private javax.swing.JTextField jtfContactNo;
    private javax.swing.JTextField jtfFatherName;
    private javax.swing.JTextField jtfName;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblStudentID;
    // End of variables declaration//GEN-END:variables
}
