/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.userscreen;

import java.io.File;
import java.io.FileInputStream;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.dao.CommonDAO;
import operations.ErrorHandler;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Grapess
 */
public class ViewCourseChart extends javax.swing.JInternalFrame {

    GregorianCalendar gcal;

    public ViewCourseChart() {
        initComponents();
        gcal = new GregorianCalendar();
        int current_year = gcal.get(Calendar.YEAR);
        jcbYear.removeAllItems();
        jcbYear.addItem("Choose Any Year");
        for (int year = 2017; year <= current_year + 1; year++) {
            jcbYear.addItem(year);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChart = new javax.swing.JLabel();
        jcbYear = new javax.swing.JComboBox();
        btnView = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Chart of Course");

        lblChart.setBackground(new java.awt.Color(153, 153, 0));

        jcbYear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnView.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnView.setText("View Chart");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jcbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbYear)
                    .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(lblChart, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        String message = "";
        if (jcbYear.getSelectedIndex() > 0) {
            int selected_year = Integer.parseInt(jcbYear.getSelectedItem().toString());
            List<Object[]> records = new CommonDAO().getCourseDetails(selected_year);
            if (records != null && records.size() > 0) {
                try {
                    DefaultCategoryDataset dataset
                            = new DefaultCategoryDataset();
                    for (Object[] record : records) {
                        dataset.addValue((int) record[1], record[0].toString(), "Total Student");
                    }
                    JFreeChart barChart = ChartFactory.createBarChart(
                            "Report " + selected_year,
                            "Category",
                            "Score",
                            dataset,
                            PlotOrientation.VERTICAL,
                            true, true, false);
                    int width = lblChart.getWidth();
                    int height = lblChart.getHeight();
                    File lineChart = new File("BarChart.jpeg");
                    ChartUtilities.saveChartAsJPEG(lineChart, barChart, width, height);
                    FileInputStream fs = new FileInputStream(lineChart);
                    byte[] imageData = new byte[fs.available()];
                    fs.read(imageData);
                    fs.close();
                    ImageIcon icon = new ImageIcon(imageData);
                    lblChart.setIcon(icon);
                } catch (Exception ex) {
                    ErrorHandler.showStackTrace(ex);
                }
            } else {
                message = "There is No Record So There is no Chart ";
            }

        }
        if (!message.isEmpty()) {
            JOptionPane.showMessageDialog(this, message);
        }
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox jcbYear;
    private javax.swing.JLabel lblChart;
    // End of variables declaration//GEN-END:variables
}
