/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.adminscreen;

import javax.swing.JOptionPane;
import model.dao.CoursesDAO;
import model.to.CoursesTO;
import operations.CommonOperations;
import operations.Validations;

/**
 *
 * @author Grapess
 */
public class AddNewCourse extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddNewCourse
     */
    public AddNewCourse() {
        initComponents();
    }

    public AddNewCourse(CoursesTO record) {
        this();
        if (record != null) {
            setTitle("Update Course Details");
            btnSave.setText("Update Course Details");
            jtfCourseID.setText(record.getCourseid());
            jtfCourseName.setText(record.getCoursename());
            jtfCourseFee.setText(String.valueOf(record.getCoursefee()));
            jtfCourseID.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfCourseID = new javax.swing.JTextField();
        jtfCourseName = new javax.swing.JTextField();
        jtfCourseFee = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add New Course Details");

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText("Enter Course ID :");

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel2.setText("Enter Course Fee :");

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel3.setText("Enter Course Name :");

        jtfCourseID.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        jtfCourseName.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        jtfCourseFee.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSave.setText("Add Course Details");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfCourseFee, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jtfCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCourseFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String message = "";
        String courseid = jtfCourseID.getText().trim();
        String coursename = jtfCourseName.getText().trim();
        String coursefee = jtfCourseFee.getText().trim();
        if (Validations.isEmpty(courseid) || Validations.isEmpty(coursename) || Validations.isEmpty(coursefee)) {
            message = "Please Fill All Boxes";
        } else if (Validations.isNumber(coursefee)) {
            int fee = Integer.parseInt(coursefee);
            if (fee > 0) {
                CoursesTO record = new CoursesTO();
                record.setCourseid(courseid);
                record.setCoursename(coursename);
                record.setCoursefee(fee);
                CoursesDAO action = new CoursesDAO();
                if (btnSave.getText().contains("Add")) {
                    if (action.insertRecord(record)) {
                        message = "Course Information is Saved in System";
                    } else {
                        message = "Insertion Failure Due To : " + action.getError_message();
                        if (message.contains("PRIMARY")) {
                            message = "Course ID is Already Available in System Database. So Try with Different Name";
                        }
                    }
                } else if (btnSave.getText().contains("Update")) {
                    if (action.updateRecord(record)) {
                        message = "Course Information is Updated in System";
                    } else {
                        message = "Updation Failure Due To : " + action.getError_message();                        
                    }
                    CommonOperations.showInternalFrame(getDesktopPane(), new ViewCourse());
                    dispose();
                } else {
                    message = "Invalid Operations";
                }
            } else {
                message = "Course Fee must be positive number";
            }
        } else {
            message = "Course Fee must be a Number";
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtfCourseFee;
    private javax.swing.JTextField jtfCourseID;
    private javax.swing.JTextField jtfCourseName;
    // End of variables declaration//GEN-END:variables
}
