/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.adminscreen;

import javax.swing.ImageIcon;
import operations.CommonOperations;

/**
 *
 * @author Grapess
 */
public class AdminMainScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminMainScreen
     */
    public AdminMainScreen() {
        try {
            ImageIcon icon;
            icon = new ImageIcon(getClass().getResource("/pics/fav.png"));
            setIconImage(icon.getImage());
        } catch (Exception ex) {
        }
        initComponents();
        setSize(1200, 650);
        setLocationRelativeTo(null);
        menuSettings.setVisible(false);
    }
    
    public AdminMainScreen(String uname) {
        this();
        if(uname.equals("master")){
            menuSettings.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskpane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCourse = new javax.swing.JMenu();
        jmiAddNewCourse = new javax.swing.JMenuItem();
        jmiViewCourse = new javax.swing.JMenuItem();
        menuStudent = new javax.swing.JMenu();
        jmiAddStudent = new javax.swing.JMenuItem();
        jmiViewStudent = new javax.swing.JMenuItem();
        menuStudentCourse = new javax.swing.JMenu();
        jmiAssignCourse = new javax.swing.JMenuItem();
        jmiViewStudentCourse = new javax.swing.JMenuItem();
        menuSettings = new javax.swing.JMenu();
        jmiChange = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout deskpaneLayout = new javax.swing.GroupLayout(deskpane);
        deskpane.setLayout(deskpaneLayout);
        deskpaneLayout.setHorizontalGroup(
            deskpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1126, Short.MAX_VALUE)
        );
        deskpaneLayout.setVerticalGroup(
            deskpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        getContentPane().add(deskpane, java.awt.BorderLayout.CENTER);

        menuCourse.setText("Course Operations");
        menuCourse.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N

        jmiAddNewCourse.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jmiAddNewCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/add.png"))); // NOI18N
        jmiAddNewCourse.setText("Add New Course");
        jmiAddNewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddNewCourseActionPerformed(evt);
            }
        });
        menuCourse.add(jmiAddNewCourse);

        jmiViewCourse.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jmiViewCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/view.png"))); // NOI18N
        jmiViewCourse.setText("View Course Details");
        jmiViewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewCourseActionPerformed(evt);
            }
        });
        menuCourse.add(jmiViewCourse);

        jMenuBar1.add(menuCourse);

        menuStudent.setText("Student Operations");
        menuStudent.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N

        jmiAddStudent.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jmiAddStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/add.png"))); // NOI18N
        jmiAddStudent.setText("Add New Student");
        jmiAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddStudentActionPerformed(evt);
            }
        });
        menuStudent.add(jmiAddStudent);

        jmiViewStudent.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jmiViewStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/view.png"))); // NOI18N
        jmiViewStudent.setText("View Student Details");
        menuStudent.add(jmiViewStudent);

        jMenuBar1.add(menuStudent);

        menuStudentCourse.setText("Student Course Operations");
        menuStudentCourse.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N

        jmiAssignCourse.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jmiAssignCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/add.png"))); // NOI18N
        jmiAssignCourse.setText("Assign Course To Student");
        jmiAssignCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAssignCourseActionPerformed(evt);
            }
        });
        menuStudentCourse.add(jmiAssignCourse);

        jmiViewStudentCourse.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jmiViewStudentCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/view.png"))); // NOI18N
        jmiViewStudentCourse.setText("View Student Course Details");
        jmiViewStudentCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewStudentCourseActionPerformed(evt);
            }
        });
        menuStudentCourse.add(jmiViewStudentCourse);

        jMenuBar1.add(menuStudentCourse);

        menuSettings.setText("Settings");
        menuSettings.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N

        jmiChange.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jmiChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/edit.png"))); // NOI18N
        jmiChange.setText("Change DB Settings");
        jmiChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiChangeActionPerformed(evt);
            }
        });
        menuSettings.add(jmiChange);

        jMenuBar1.add(menuSettings);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAddNewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddNewCourseActionPerformed
        CommonOperations.showInternalFrame(deskpane, new AddNewCourse());
    }//GEN-LAST:event_jmiAddNewCourseActionPerformed

    private void jmiViewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewCourseActionPerformed
        CommonOperations.showInternalFrame(deskpane, new ViewCourse());
    }//GEN-LAST:event_jmiViewCourseActionPerformed

    private void jmiAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddStudentActionPerformed
        CommonOperations.showInternalFrame(deskpane, new AddStudents());
    }//GEN-LAST:event_jmiAddStudentActionPerformed

    private void jmiAssignCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAssignCourseActionPerformed
        CommonOperations.showInternalFrame(deskpane, new AssignStudentCourse());
    }//GEN-LAST:event_jmiAssignCourseActionPerformed

    private void jmiViewStudentCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewStudentCourseActionPerformed
        CommonOperations.showInternalFrame(deskpane, new ViewStudentCourses());
    }//GEN-LAST:event_jmiViewStudentCourseActionPerformed

    private void jmiChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiChangeActionPerformed
        CommonOperations.showInternalFrame(deskpane, new ChangeDBSettings());
    }//GEN-LAST:event_jmiChangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskpane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiAddNewCourse;
    private javax.swing.JMenuItem jmiAddStudent;
    private javax.swing.JMenuItem jmiAssignCourse;
    private javax.swing.JMenuItem jmiChange;
    private javax.swing.JMenuItem jmiViewCourse;
    private javax.swing.JMenuItem jmiViewStudent;
    private javax.swing.JMenuItem jmiViewStudentCourse;
    private javax.swing.JMenu menuCourse;
    private javax.swing.JMenu menuSettings;
    private javax.swing.JMenu menuStudent;
    private javax.swing.JMenu menuStudentCourse;
    // End of variables declaration//GEN-END:variables
}
