/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens.adminscreen;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.util.Locale;
import java.util.Properties;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author Grapess
 */
public class ChangeDBSettings extends javax.swing.JInternalFrame {

    String culture;
    public ChangeDBSettings() {
        initComponents();
        ResourceBundle rb;
        rb = ResourceBundle.getBundle("config.Configuration");
        jtfDriverName.setText(rb.getString("DRIVER_NAME"));
        jtfDBUser.setText(rb.getString("DB_USER"));
        jtfConnectionURL.setText(rb.getString("CONNECTION_URL"));
        jtfDBPassword.setText(rb.getString("DB_PASS"));
        rb = ResourceBundle.getBundle("config.Culture");
        culture = rb.getString("CULTURE");
        if(culture.equalsIgnoreCase("English")){
            btnChange1.setText("Change to French");
        }else{
            btnChange1.setText("Change to English");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfDriverName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfConnectionURL = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfDBUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfDBPassword = new javax.swing.JTextField();
        btnChange = new javax.swing.JButton();
        btnChange1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Change DB Settings");

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText("Driver Name :");

        jtfDriverName.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel2.setText("Connection URL :");

        jtfConnectionURL.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel3.setText("DB User :");

        jtfDBUser.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel4.setText("DB Password :");

        jtfDBPassword.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        btnChange.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnChange.setText("Change Details");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnChange1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnChange1.setText("Change To French");
        btnChange1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChange1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDBPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDriverName, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDBUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfConnectionURL, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChange1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfDriverName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfConnectionURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfDBUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfDBPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChange1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        String driver_name = jtfDriverName.getText().trim();
        String connection_url = jtfConnectionURL.getText().trim();
        String db_user = jtfDBUser.getText().trim();
        String db_pass = jtfDBPassword.getText().trim();
        String message = "";
        try {
            OutputStream os = null;
            Properties prop = new Properties();
            prop.setProperty("DRIVER_NAME", driver_name);
            prop.setProperty("CONNECTION_URL", connection_url);
            prop.setProperty("DB_USER", db_user);
            prop.setProperty("DB_PASS", db_pass);
            File file =new File(getClass().getResource("/config/Configuration.properties").toURI());
            os = new FileOutputStream(file);
            prop.store(os, "Configuration Details");
            ResourceBundle rb = ResourceBundle.getBundle("config.Messages");
            if(culture.equalsIgnoreCase("french")){
                rb = ResourceBundle.getBundle("config.Messages",Locale.FRENCH);
            }
            message = rb.getString("message");
        } catch (Exception ex) {
            message = ex.toString();
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnChange1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChange1ActionPerformed
        String message = "";
        try {
            OutputStream os = null;
            Properties prop = new Properties();
            if(culture.equalsIgnoreCase("english")){
                prop.setProperty("CULTURE", "French");
                culture = "French";
                btnChange1.setText("Change to English");
            }else{
                prop.setProperty("CULTURE", "English");
                culture = "English";
                btnChange1.setText("Change to French");
            }
            File file =new File(getClass().getResource("/config/Culture.properties").toURI());
            os = new FileOutputStream(file);
            prop.store(os, "Configuration Details");
            message = "Settings Changed";
        } catch (Exception ex) {
            message = ex.toString();
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnChange1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnChange1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtfConnectionURL;
    private javax.swing.JTextField jtfDBPassword;
    private javax.swing.JTextField jtfDBUser;
    private javax.swing.JTextField jtfDriverName;
    // End of variables declaration//GEN-END:variables
}
